#!/usr/bin/env node

/**
 * Build the React website from upstream aws-samples/document-translation.
 *
 * Clones the upstream repo (if not already cached), copies the website source,
 * patches it for runtime config loading (ISB compatibility), and builds it.
 * Output goes to ./website-build/.
 *
 * Upstream: https://github.com/aws-samples/document-translation (v3.4.0)
 * License: MIT-0
 *
 * Patch: The upstream app uses build-time config via require("../cfnOutputs.json").
 * We patch amplifyConfigure.tsx to load config at runtime from /config.js,
 * allowing the CloudFormation Custom Resource to inject values at deploy time.
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const UPSTREAM_REPO = "https://github.com/aws-samples/document-translation.git";
const UPSTREAM_TAG = "v3.4.0";
const UPSTREAM_CACHE = path.resolve(__dirname, "../.upstream");
const UPSTREAM_WEBSITE_DIR = path.join(UPSTREAM_CACHE, "website");
const OUTPUT_DIR = path.resolve(__dirname, "../website-build");
const BUILD_DIR = path.resolve(__dirname, "../.website-build-tmp");

function ensureUpstream() {
  if (fs.existsSync(UPSTREAM_WEBSITE_DIR)) {
    console.log("  Using cached upstream clone.");
    return;
  }
  console.log(`  Cloning ${UPSTREAM_REPO} @ ${UPSTREAM_TAG}...`);
  execSync(
    `git clone --depth 1 --branch "${UPSTREAM_TAG}" "${UPSTREAM_REPO}" "${UPSTREAM_CACHE}"`,
    { stdio: "pipe" }
  );
}

console.log("Building React website from upstream document-translation...");
ensureUpstream();
console.log(`  Source: ${UPSTREAM_WEBSITE_DIR}`);
console.log(`  Output: ${OUTPUT_DIR}`);

if (!fs.existsSync(UPSTREAM_WEBSITE_DIR)) {
  console.error(
    "ERROR: Upstream website not found. Clone may have failed."
  );
  process.exit(1);
}

// Clean build dir
if (fs.existsSync(BUILD_DIR)) {
  fs.rmSync(BUILD_DIR, { recursive: true });
}

// Copy website source to temp build dir
console.log("\n1. Copying website source...");
execSync(`cp -r "${UPSTREAM_WEBSITE_DIR}" "${BUILD_DIR}"`);

// Create minimal config files needed for build
console.log("2. Creating build-time config stubs...");

// features.json - enable both features
fs.writeFileSync(
  path.join(BUILD_DIR, "src", "features.json"),
  JSON.stringify({ translation: true, readable: true }, null, 2)
);

// cfnOutputs.json - stub values (replaced at runtime by config.js)
fs.writeFileSync(
  path.join(BUILD_DIR, "src", "cfnOutputs.json"),
  JSON.stringify(
    {
      awsUserPoolsId: "PLACEHOLDER",
      awsUserPoolsWebClientId: "PLACEHOLDER",
      awsCognitoIdentityPoolId: "PLACEHOLDER",
      awsCognitoOauthDomain: "PLACEHOLDER",
      awsRegion: "us-east-1",
      awsCognitoOauthRedirectSignIn: "https://placeholder.cloudfront.net",
      awsCognitoOauthRedirectSignOut: "https://placeholder.cloudfront.net",
      awsAppsyncGraphqlEndpoint: "https://placeholder.appsync-api.us-east-1.amazonaws.com/graphql",
      awsUserFilesS3Bucket: "placeholder-bucket",
      awsTranslationFilesS3Bucket: "placeholder-bucket",
      awsReadableFilesS3Bucket: "placeholder-bucket",
      awsReadableS3Bucket: "placeholder-bucket",
    },
    null,
    2
  )
);

// GraphQL operation stubs - normally generated by Amplify codegen from AppSync schema.
// These are just GraphQL operation strings; the actual schema lives in AppSync at runtime.
console.log("3. Creating GraphQL operation stubs...");
const graphqlDir = path.join(BUILD_DIR, "src", "graphql");
fs.mkdirSync(graphqlDir, { recursive: true });

fs.writeFileSync(
  path.join(graphqlDir, "mutations.ts"),
  `// Auto-generated stubs for build compatibility — must use individual args (not input types)
export const translationCreateJob = /* GraphQL */ \`mutation TranslationCreateJob($input: translation_createJob_input!) { translationCreateJob(input: $input) { id jobIdentity } }\`;
export const readableCreateJob = /* GraphQL */ \`mutation ReadableCreateJob($identity: String!) { readableCreateJob(identity: $identity) { id identity } }\`;
export const readableCreateJobImport = /* GraphQL */ \`mutation ReadableCreateJobImport($id: ID!, $identity: String, $order: Int, $type: String, $modelId: String, $status: String, $key: String) { readableCreateJobImport(id: $id, identity: $identity, order: $order, type: $type, modelId: $modelId, status: $status, key: $key) { id } }\`;
export const readableCreateJobItem = /* GraphQL */ \`mutation ReadableCreateJobItem($order: Int!, $identity: String!, $type: String!, $id: ID!, $parent: String, $input: String, $modelId: String, $output: String, $owner: String, $status: String) { readableCreateJobItem(order: $order, identity: $identity, type: $type, id: $id, parent: $parent, input: $input, modelId: $modelId, output: $output, owner: $owner, status: $status) { id itemId order identity type parent input modelId owner output status } }\`;
export const readableUpdateJobItem = /* GraphQL */ \`mutation ReadableUpdateJobItem($order: Int, $itemId: ID!, $type: String, $identity: String, $id: ID!, $parent: String, $input: String, $modelId: String, $output: String, $owner: String, $status: String) { readableUpdateJobItem(order: $order, itemId: $itemId, type: $type, identity: $identity, id: $id, parent: $parent, input: $input, modelId: $modelId, output: $output, owner: $owner, status: $status) { id itemId type order identity parent input modelId owner output status } }\`;
export const readableUpdateJobMetadata = /* GraphQL */ \`mutation ReadableUpdateJobMetadata($id: String!, $name: String) { readableUpdateJobMetadata(id: $id, name: $name) { id name createdAt owner updatedAt } }\`;
export const sharedUpdatePreferences = /* GraphQL */ \`mutation SharedUpdatePreferences($visualMode: String, $visualDensity: String) { sharedUpdatePreferences(visualMode: $visualMode, visualDensity: $visualDensity) { id } }\`;
`
);

fs.writeFileSync(
  path.join(graphqlDir, "queries.ts"),
  `// Auto-generated stubs for build compatibility
export const translationListJobs = /* GraphQL */ \`query TranslationListJobs { translationListJobs { items { id jobOwner jobName createdAt jobStatus languageSource languageTargets translateKey } nextToken } }\`;
export const readableListJobs = /* GraphQL */ \`query ReadableListJobs { readableListJobs { items { id identity name createdAt updatedAt } nextToken } }\`;
export const readableGetJob = /* GraphQL */ \`query ReadableGetJob($id: ID!) { readableGetJob(id: $id) { items { id itemId identity name createdAt updatedAt input modelId order output parent status type } } }\`;
export const readableListModels = /* GraphQL */ \`query ReadableListModels { readableListModels { items { id name modelId type } } }\`;
export const readableListPrintStyles = /* GraphQL */ \`query ReadableListPrintStyles { readableListPrintStyles { items { id name } } }\`;
export const sharedGetPreferences = /* GraphQL */ \`query SharedGetPreferences { sharedGetPreferences { id visualMode visualDensity } }\`;
export const helpListHelps = /* GraphQL */ \`query HelpListHelps { helpListHelps { items { id } } }\`;
`
);

fs.writeFileSync(
  path.join(graphqlDir, "subscriptions.ts"),
  `// Auto-generated stubs for build compatibility
export const readableUpdateJobItem = /* GraphQL */ \`subscription ReadableUpdateJobItem($id: ID!) { readableUpdateJobItem(id: $id) { id itemId type order identity parent input modelId owner output status } }\`;
`
);

// Patch amplifyConfigure.tsx to load config from window.__DOCTRAN_CONFIG__ at runtime
console.log("4. Patching for runtime config loading...");
const amplifyCfgPath = path.join(
  BUILD_DIR,
  "src",
  "util",
  "amplifyConfigure.tsx"
);
if (fs.existsSync(amplifyCfgPath)) {
  let content = fs.readFileSync(amplifyCfgPath, "utf8");
  // Replace the static require with runtime config from window
  content = content.replace(
    /const cfnOutputs = require\(["']\.\.\/cfnOutputs\.json["']\);?/,
    "const cfnOutputs = (window as any).__DOCTRAN_CONFIG__ || require('../cfnOutputs.json');"
  );
  fs.writeFileSync(amplifyCfgPath, content);
  console.log("   Patched amplifyConfigure.tsx for runtime config");
} else {
  console.warn("   WARN: amplifyConfigure.tsx not found at expected path");
}

// Also patch configureS3Bucket.tsx — it has its own require("../cfnOutputs.json")
const configureS3Path = path.join(
  BUILD_DIR,
  "src",
  "util",
  "configureS3Bucket.tsx"
);
if (fs.existsSync(configureS3Path)) {
  let s3Content = fs.readFileSync(configureS3Path, "utf8");
  s3Content = s3Content.replace(
    /const cfnOutputs = require\(["']\.\.\/cfnOutputs\.json["']\);?/,
    "const cfnOutputs = (window as any).__DOCTRAN_CONFIG__ || require('../cfnOutputs.json');"
  );
  fs.writeFileSync(configureS3Path, s3Content);
  console.log("   Patched configureS3Bucket.tsx for runtime config");
}

// Also patch useGetPresignedUrl.tsx — it imports cfnOutputs directly
const presignedUrlPath = path.join(
  BUILD_DIR,
  "src",
  "page",
  "readable",
  "hooks",
  "useGetPresignedUrl.tsx"
);
if (fs.existsSync(presignedUrlPath)) {
  let presignedContent = fs.readFileSync(presignedUrlPath, "utf8");
  presignedContent = presignedContent.replace(
    /const cfnOutputs = require\(["'].*?cfnOutputs\.json["']\);?/,
    "const cfnOutputs = (window as any).__DOCTRAN_CONFIG__ || require('../../../cfnOutputs.json');"
  );
  fs.writeFileSync(presignedUrlPath, presignedContent);
  console.log("   Patched useGetPresignedUrl.tsx for runtime config");
}

// Install deps and build
console.log("5. Installing dependencies...");
execSync("npm install", { cwd: BUILD_DIR, stdio: "pipe" });

// Patch fork-ts-checker-webpack-plugin for Node 18+ compatibility
// (typescript.performance properties became read-only getters)
console.log("   Patching fork-ts-checker-webpack-plugin...");
const tsPerfPath = path.join(
  BUILD_DIR,
  "node_modules",
  "fork-ts-checker-webpack-plugin",
  "lib",
  "typescript-reporter",
  "profile",
  "TypeScriptPerformance.js"
);
if (fs.existsSync(tsPerfPath)) {
  fs.writeFileSync(
    tsPerfPath,
    `"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function connectTypeScriptPerformance(typescript, performance) {
  return performance;
}
exports.connectTypeScriptPerformance = connectTypeScriptPerformance;
`
  );
}

console.log("6. Building React app (this may take a minute)...");
execSync("npm run build", {
  cwd: BUILD_DIR,
  stdio: "pipe",
  env: {
    ...process.env,
    GENERATE_SOURCEMAP: "false", // No source maps in output
    CI: "true",
    TSC_COMPILE_ON_ERROR: "true", // Allow TS type mismatches from version drift
  },
});

// Copy build output
console.log("7. Copying build output...");
const reactBuildDir = path.join(BUILD_DIR, "build");
if (!fs.existsSync(reactBuildDir)) {
  console.error("ERROR: React build output not found at", reactBuildDir);
  process.exit(1);
}

if (fs.existsSync(OUTPUT_DIR)) {
  fs.rmSync(OUTPUT_DIR, { recursive: true });
}
execSync(`cp -r "${reactBuildDir}" "${OUTPUT_DIR}"`);

// Add runtime config.js placeholder
fs.writeFileSync(
  path.join(OUTPUT_DIR, "config.js"),
  `// This file is replaced at deploy time by the Custom Resource
// with real CloudFormation output values.
// window.__DOCTRAN_CONFIG__ = { awsRegion: "us-east-1", ... };
`
);

// Inject <script src="/config.js"> into index.html before the main bundle
console.log("8. Injecting config.js script tag into index.html...");
const indexPath = path.join(OUTPUT_DIR, "index.html");
let indexHtml = fs.readFileSync(indexPath, "utf8");
// Fix Amplify oauthSignIn localStorage corruption: the Cognito hosted UI
// OAuth flow sets this to "true,false" which causes fetchAuthSession() to hang.
const oauthFix = `<script>try{Object.keys(localStorage).filter(k=>k.endsWith('.oauthSignIn')).forEach(k=>{var v=localStorage.getItem(k);if(v&&v!=='true'&&v!=='false')localStorage.setItem(k,'false')})}catch(e){}</script>`;
indexHtml = indexHtml.replace(
  '<script defer="defer" src="/static/js/main',
  `<script src="/config.js"></script>${oauthFix}<script defer="defer" src="/static/js/main`
);
fs.writeFileSync(indexPath, indexHtml);

// Clean up
fs.rmSync(BUILD_DIR, { recursive: true });

const fileCount = execSync(`find "${OUTPUT_DIR}" -type f | wc -l`)
  .toString()
  .trim();
console.log(`\nWebsite build complete: ${fileCount} files in website-build/`);
