"""Share PDF builder Lambda.

Per tech-spec Task 6.7. Reads ONLY from the redacted DynamoDB cache and the
Cases-domain redacted fields; never touches OriginalSegment. Generates a PDF
with fpdf2 (pure Python, bundled in the Lambda package via requirements.txt)
and returns a presigned S3 URL with TTL up to 86400 seconds.
"""

import io
import logging
import os
import time
from typing import Any, Dict, List

import boto3
from fpdf import FPDF

logger = logging.getLogger()
logger.setLevel(logging.INFO)

DDB_TABLE_NAME = os.environ["DDB_TABLE_NAME"]
SHARE_BUCKET = os.environ["SHARE_BUCKET"]
SHARE_PRESIGN_TTL = int(os.environ.get("SHARE_PRESIGN_TTL", "86400"))
CASES_DOMAIN_ID = os.environ["CASES_DOMAIN_ID"]

s3 = boto3.client("s3")
ddb = boto3.resource("dynamodb")
cases = boto3.client("connectcases")


def lambda_handler(event, context):
    contact_id = event.get("contact_id")
    case_id = event.get("case_id")
    if not contact_id and not case_id:
        return {"error": "contact_id or case_id required"}

    pdf_bytes = _build_pdf(contact_id, case_id)
    key = f"share-pdfs/{int(time.time())}-{(contact_id or case_id)[:24]}.pdf"
    s3.put_object(Bucket=SHARE_BUCKET, Key=key, Body=pdf_bytes, ContentType="application/pdf")
    url = s3.generate_presigned_url(
        "get_object",
        Params={"Bucket": SHARE_BUCKET, "Key": key},
        ExpiresIn=SHARE_PRESIGN_TTL,
    )
    return {"share_url": url, "ttl": SHARE_PRESIGN_TTL, "key": key}


def _build_pdf(contact_id: str, case_id: str) -> bytes:
    transcript_segments: List[Dict[str, Any]] = []
    if contact_id:
        table = ddb.Table(DDB_TABLE_NAME)
        resp = table.query(
            KeyConditionExpression="contactId = :c",
            ExpressionAttributeValues={":c": contact_id},
            ScanIndexForward=True,
        )
        transcript_segments = resp.get("Items", [])

    case_summary: Dict[str, Any] = {}
    if case_id:
        case_summary = _fetch_case(case_id)

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", size=18, style="B")
    pdf.cell(0, 10, "AI Contact Centre, share", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(0, 5,
        "This is a redacted, demonstration share document from an NDX:Try AI "
        "Contact Centre lease. Personal information has been redacted at the "
        "Connect instance level; only redacted segments appear here. The "
        "presigned URL for this document expires within 24 hours of generation.")
    pdf.ln(4)

    if case_summary:
        pdf.set_font("Helvetica", size=14, style="B")
        pdf.cell(0, 8, "Connect Case", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", size=10)
        for k, v in case_summary.items():
            pdf.set_font("Helvetica", size=10, style="B")
            pdf.cell(50, 6, str(k))
            pdf.set_font("Helvetica", size=10)
            pdf.multi_cell(0, 6, str(v) if v is not None else "")
        pdf.ln(4)

    if transcript_segments:
        pdf.set_font("Helvetica", size=14, style="B")
        pdf.cell(0, 8, "Redacted call transcript", new_x="LMARGIN", new_y="NEXT")
        for seg in transcript_segments:
            ts = seg.get("segmentTimestamp", 0)
            speaker = seg.get("speaker", "?")
            text = seg.get("transcript", "")
            pdf.set_font("Helvetica", size=10, style="B")
            pdf.cell(40, 5, f"{speaker} ({ts})")
            pdf.set_font("Helvetica", size=10)
            pdf.multi_cell(0, 5, text)
        pdf.ln(4)

    pdf.set_font("Helvetica", size=8, style="I")
    pdf.cell(0, 5, "Generated by NDX:Try AI Contact Centre demo. Do not share publicly.",
             new_x="LMARGIN", new_y="NEXT")

    out = pdf.output(dest="S")
    return bytes(out) if isinstance(out, bytearray) else out.encode("latin-1") if isinstance(out, str) else out


def _fetch_case(case_id: str) -> Dict[str, Any]:
    try:
        resp = cases.get_case(
            domainId=CASES_DOMAIN_ID,
            caseId=case_id,
            fields=[
                {"id": "title"}, {"id": "intent_category"}, {"id": "severity"},
                {"id": "multimodal_summary"}, {"id": "safeguarding_flag"},
            ],
        )
    except Exception as exc:
        logger.warning("get_case failed: %s", exc)
        return {}
    out = {}
    for f in resp.get("fields", []):
        v = f.get("value", {})
        out[f.get("id")] = next(iter(v.values()), None)
    return out
