AWSTemplateFormatVersion: '2010-09-09'
Description: |
  NDX Reference Stack Sample Data Loader
  Story: S0.5 - Reference Deployment Environment

  Pre-loads known-good sample data for all 6 scenarios via Lambda custom resources.

  AC5.3: Known-good sample data preloaded for all 6 scenarios

Parameters:
  ReferenceStackName:
    Type: String
    Default: 'ndx-reference'
    Description: Name of the reference stack to load data into

Resources:
  # ==========================================================================
  # Sample Data Loader Lambda
  # ==========================================================================
  SampleDataLoaderFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ndx-reference-sample-data-loader
      Runtime: nodejs20.x
      Handler: index.handler
      Timeout: 300
      MemorySize: 512
      Role: !GetAtt SampleDataLoaderRole.Arn
      Code:
        ZipFile: |
          const { DynamoDBClient, PutItemCommand, BatchWriteItemCommand } = require('@aws-sdk/client-dynamodb');
          const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
          const { CloudFormationClient, DescribeStacksCommand } = require('@aws-sdk/client-cloudformation');

          const dynamoClient = new DynamoDBClient({});
          const s3Client = new S3Client({});
          const cfnClient = new CloudFormationClient({});

          const sendResponse = async (event, context, status, data) => {
            const https = require('https');
            const url = require('url');

            const responseBody = JSON.stringify({
              Status: status,
              Reason: data?.reason || `See CloudWatch Log Stream: ${context.logStreamName}`,
              PhysicalResourceId: data?.physicalResourceId || context.logStreamName,
              StackId: event.StackId,
              RequestId: event.RequestId,
              LogicalResourceId: event.LogicalResourceId,
              Data: data?.attributes || {}
            });

            const parsedUrl = url.parse(event.ResponseURL);
            const options = {
              hostname: parsedUrl.hostname,
              port: 443,
              path: parsedUrl.path,
              method: 'PUT',
              headers: {
                'Content-Type': '',
                'Content-Length': responseBody.length
              }
            };

            return new Promise((resolve, reject) => {
              const request = https.request(options, (response) => {
                resolve();
              });
              request.on('error', (error) => {
                console.error('sendResponse Error:', error);
                resolve();
              });
              request.write(responseBody);
              request.end();
            });
          };

          exports.handler = async (event, context) => {
            console.log('Event:', JSON.stringify(event));

            try {
              if (event.RequestType === 'Delete') {
                await sendResponse(event, context, 'SUCCESS', {
                  physicalResourceId: 'SampleDataLoader'
                });
                return;
              }

              if (event.RequestType === 'Create' || event.RequestType === 'Update') {
                // Load sample data for all scenarios
                const accountId = context.invokedFunctionArn.split(':')[4];

                // Scenario 1: Council Chatbot - Load sample conversations
                const chatbotItems = [
                  {
                    PutRequest: {
                      Item: {
                        conversationId: { S: 'conv-001' },
                        timestamp: { N: Date.now().toString() },
                        question: { S: 'What are the bin collection days?' },
                        response: { S: 'Your bin collection day is Thursday.' }
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        conversationId: { S: 'conv-002' },
                        timestamp: { N: (Date.now() + 1000).toString() },
                        question: { S: 'How do I apply for a parking permit?' },
                        response: { S: 'You can apply online at our parking portal.' }
                      }
                    }
                  }
                ];

                await dynamoClient.send(new BatchWriteItemCommand({
                  RequestItems: {
                    'ndx-reference-chatbot-conversations': chatbotItems
                  }
                }));

                // Scenario 2: Planning AI - Upload sample PDF
                await s3Client.send(new PutObjectCommand({
                  Bucket: `ndx-reference-planning-ai-${accountId}`,
                  Key: 'sample-planning-application.pdf',
                  Body: 'Sample planning application document for screenshot testing',
                  ContentType: 'application/pdf'
                }));

                // Scenario 3: FOI Redaction - Upload sample document
                await s3Client.send(new PutObjectCommand({
                  Bucket: `ndx-reference-foi-redaction-${accountId}`,
                  Key: 'sample-foi-request.txt',
                  Body: 'Sample FOI request document with PII: John Smith, 123 Main St, john@example.com',
                  ContentType: 'text/plain'
                }));

                // Scenario 4: Smart Car Park - Load sensor data
                const sensorItems = [
                  {
                    PutRequest: {
                      Item: {
                        sensorId: { S: 'sensor-001' },
                        timestamp: { N: Date.now().toString() },
                        occupied: { BOOL: true },
                        location: { S: 'Level 1, Bay 5' }
                      }
                    }
                  },
                  {
                    PutRequest: {
                      Item: {
                        sensorId: { S: 'sensor-002' },
                        timestamp: { N: (Date.now() + 1000).toString() },
                        occupied: { BOOL: false },
                        location: { S: 'Level 1, Bay 6' }
                      }
                    }
                  }
                ];

                await dynamoClient.send(new BatchWriteItemCommand({
                  RequestItems: {
                    'ndx-reference-car-park-sensors': sensorItems
                  }
                }));

                // Scenario 5: Text-to-Speech - Upload sample audio
                await s3Client.send(new PutObjectCommand({
                  Bucket: `ndx-reference-text-to-speech-${accountId}`,
                  Key: 'sample-announcement.mp3',
                  Body: 'Sample audio file placeholder',
                  ContentType: 'audio/mpeg'
                }));

                // Scenario 6: QuickSight - Data would be loaded separately via QuickSight API
                console.log('Sample data loaded successfully for all scenarios');

                await sendResponse(event, context, 'SUCCESS', {
                  physicalResourceId: 'SampleDataLoader',
                  attributes: {
                    Status: 'Loaded'
                  }
                });
                return;
              }

            } catch (error) {
              console.error('Error loading sample data:', error);
              await sendResponse(event, context, 'FAILED', {
                physicalResourceId: 'SampleDataLoader',
                reason: error.message
              });
              throw error;
            }
          };

  SampleDataLoaderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SampleDataLoadPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ndx-reference-*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub 'arn:aws:s3:::ndx-reference-*/*'
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource:
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ReferenceStackName}/*'

  # ==========================================================================
  # Custom Resource to Trigger Sample Data Loading
  # ==========================================================================
  LoadSampleData:
    Type: Custom::LoadSampleData
    Properties:
      ServiceToken: !GetAtt SampleDataLoaderFunction.Arn
      ReferenceStackName: !Ref ReferenceStackName

Outputs:
  SampleDataStatus:
    Description: Status of sample data loading
    Value: !GetAtt LoadSampleData.Status
