import * as crypto from 'crypto';
import * as cdk from 'aws-cdk-lib';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as appregistry from 'aws-cdk-lib/aws-servicecatalogappregistry';
import { Construct, IConstruct } from 'constructs';
import { CloudFrontConstruct } from './constructs/cloudfront';
import { ComputeConstruct } from './constructs/compute';
import { DatabaseConstruct } from './constructs/database';
import { NetworkingConstruct } from './constructs/networking';
import { StorageConstruct } from './constructs/storage';

/**
 * CDK Aspect that ensures all IAM roles have ISB SCP-compliant names.
 * Uses full construct path + MD5 hash to guarantee uniqueness.
 */
class IsbRoleNamingAspect implements cdk.IAspect {
  visit(node: IConstruct): void {
    if (node instanceof iam.CfnRole) {
      const currentName = node.roleName;
      if (!currentName || !currentName.toString().startsWith('InnovationSandbox-ndx-')) {
        const fullPath = node.node.path;
        const hash = crypto.createHash('md5').update(fullPath).digest('hex').substring(0, 8);
        const meaningful = fullPath
          .replace(/[A-F0-9]{8}$/, '')
          .replace(/[^a-zA-Z0-9-]/g, '')
          .slice(-33);
        node.roleName = `InnovationSandbox-ndx-${meaningful}-${hash}`;
      }
    }
  }
}

export class PlanxStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Apply ISB role naming aspect
    cdk.Aspects.of(this).add(new IsbRoleNamingAspect());

    // Tags
    cdk.Tags.of(this).add('Project', 'ndx-try-aws-scenarios');
    cdk.Tags.of(this).add('Scenario', 'planx');

    // AppRegistry Application
    const appRegistryApp = new appregistry.CfnApplication(this, 'AppRegistryApplication', {
      name: `NDXTry_PlanX_${this.account}`,
      description: 'NDX:Try - PlanX Digital Planning Platform',
      tags: { Project: 'ndx-try', Scenario: 'planx' },
    });

    new appregistry.CfnResourceAssociation(this, 'AppRegistryAssociation', {
      application: appRegistryApp.attrId,
      resource: this.stackId,
      resourceType: 'CFN_STACK',
    });

    cdk.Tags.of(this).add('awsApplication', appRegistryApp.attrArn, {
      excludeResourceTypes: [
        'AWS::ServiceCatalogAppRegistry::Application',
        'AWS::ServiceCatalogAppRegistry::ResourceAssociation',
      ],
    });

    // No Secrets Manager secrets for app secrets — ISB SCP blocks runtime SM access,
    // and SM dynamic references don't resolve in CloudFormation Outputs.
    // All secrets are generated by the PasswordGenFn Lambda custom resource below.

    // Lambda-backed custom resource that generates passwords and returns them
    // as CloudFormation attributes — so they can be shown in plaintext in Outputs.
    // (Secrets Manager dynamic references don't resolve in Outputs.)
    const pwGenRole = new iam.Role(this, 'PasswordGenRole', {
      roleName: 'InnovationSandbox-ndx-planx-pwgen',
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AWSLambdaBasicExecutionRole'),
      ],
    });

    const pwGenFn = new lambda.Function(this, 'PasswordGenFn', {
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      role: pwGenRole,
      timeout: cdk.Duration.seconds(30),
      code: lambda.Code.fromInline(`
const crypto=require("crypto");const https=require("https");
exports.handler=async(e)=>{
  const rp={Status:"SUCCESS",PhysicalResourceId:e.LogicalResourceId,StackId:e.StackId,RequestId:e.RequestId,LogicalResourceId:e.LogicalResourceId};
  try{
    if(e.RequestType==="Create"||e.RequestType==="Update"){
      const gen=(n)=>crypto.randomBytes(n).toString("base64url").slice(0,n);
      rp.Data={DemoPassword:gen(16),HasuraAdminSecret:gen(32),JwtSecret:gen(64),SessionSecret:gen(64),EncryptionKey:gen(32)};
    }else{rp.Data={}}
    await send(e.ResponseURL,rp);
  }catch(err){rp.Status="FAILED";rp.Reason=err.message;await send(e.ResponseURL,rp)}
};
function send(u,d){return new Promise((ok,fail)=>{const b=JSON.stringify(d);const o=new URL(u);const opts={hostname:o.hostname,port:443,path:o.pathname+o.search,method:"PUT",headers:{"Content-Type":"","Content-Length":b.length}};const req=https.request(opts,ok);req.on("error",fail);req.write(b);req.end()})}`),
    });

    const passwords = new cdk.CfnCustomResource(this, 'Passwords', {
      serviceToken: pwGenFn.functionArn,
    });
    passwords.node.addDependency(pwGenRole);

    // Resolve secrets — use SM for internal secrets, custom resource for user-visible ones
    const resolvedSecrets = {
      jwtSecret: cdk.Fn.getAtt(passwords.logicalId, 'JwtSecret').toString(),
      hasuraAdminSecret: cdk.Fn.getAtt(passwords.logicalId, 'HasuraAdminSecret').toString(),
      sessionSecret: cdk.Fn.getAtt(passwords.logicalId, 'SessionSecret').toString(),
      encryptionKey: cdk.Fn.getAtt(passwords.logicalId, 'EncryptionKey').toString(),
      demoPassword: cdk.Fn.getAtt(passwords.logicalId, 'DemoPassword').toString(),
    };

    // Networking
    const networking = new NetworkingConstruct(this, 'Networking');

    // Database
    const database = new DatabaseConstruct(this, 'Database', {
      vpc: networking.vpc,
      securityGroup: networking.auroraSecurityGroup,
    });

    // Storage (S3)
    const storage = new StorageConstruct(this, 'Storage');

    // Compute (ECS + ALB) — editor uses relative paths, no CF domain needed
    const compute = new ComputeConstruct(this, 'Compute', {
      vpc: networking.vpc,
      albSecurityGroup: networking.albSecurityGroup,
      fargateSecurityGroup: networking.fargateSecurityGroup,
      databaseCluster: database.cluster,
      databaseSecret: database.secret,
      uploadsBucket: storage.bucket,
      secrets: resolvedSecrets,
    });

    // CloudFront wraps ALB with HTTPS
    const cdn = new CloudFrontConstruct(this, 'CDN', {
      loadBalancer: compute.loadBalancer,
    });

    // CloudFormation Outputs
    new cdk.CfnOutput(this, 'PlanXUrl', {
      description: 'PlanX editor URL (HTTPS via CloudFront)',
      value: `https://${cdn.domainName}`,
    });

    new cdk.CfnOutput(this, 'PlanXLoginUrl', {
      description: 'PlanX demo login page',
      value: `https://${cdn.domainName}/api/auth/demo`,
    });

    new cdk.CfnOutput(this, 'DemoUsername', {
      description: 'Demo user email',
      value: 'demo@ndx-demo.example.com',
    });

    new cdk.CfnOutput(this, 'DemoPassword', {
      description: 'Demo user password',
      value: resolvedSecrets.demoPassword,
    });

    new cdk.CfnOutput(this, 'HasuraConsoleUrl', {
      description: 'Hasura GraphQL console',
      value: `https://${cdn.domainName}/console/`,
    });

    new cdk.CfnOutput(this, 'HasuraAdminSecretOutput', {
      description: 'Hasura admin secret (for console access)',
      value: resolvedSecrets.hasuraAdminSecret,
    });

    new cdk.CfnOutput(this, 'StackDescription', {
      description: 'Stack description',
      value: 'PlanX Digital Planning Platform - NDX:Try',
    });
  }
}
