[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:fixmystreet]
command=/var/www/fixmystreet/fixmystreet/script/fixmystreet_app_server.pl -p 9000 --fork
directory=/var/www/fixmystreet/fixmystreet
user=fms
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
